### PR TITLE
Add custom board height and width message methods to game

### LINKED ISSUE #26: Board - Dynamic Sizing
The board currently has dynamic sizing capabilities but does not explore the restrictions these might face.

Current capabilities/limitations:
- Boards with dimensions up to 9 
- Square and rectangular boards

Required changes:
- Needs receive user input to pick board size at the beginning of the game
- Needs to validate this input to meet the limitations above

Possible improvements:
- Refactor so that it can handle bigger board sizes

### PR DESCRIPTION
**Pull request by ryandbarnett**
This is the simplest way I found to get the dynamic sizing to work.

### CODE REVIEW

**Review by AngelaGuardia — CHANGES_REQUESTED** [review]
Nice job! That was quick.

I think that looks good. I would personally make the messages shorter just for aesthetics.

I think we should give a min value of 4 for both height and width. Just to ensure that our ships will fit.

**Comment by ryandbarnett** [comment]
I will add a min value of 4!

**Comment by ryandbarnett** [comment]
I have changed both methods to only allow 4-9 as input

**Review by AngelaGuardia — APPROVED** [review]
Looks good!

**Pull request merged**
